sudo: required
dist: trusty

language: cpp

compiler: gcc

before_script:
-  sudo apt-get update
-  sudo apt-get install -y ragel  libboost-all-dev libyaml-dev  postgresql-server-dev-all  zlib1g-dev liblzma-dev  gawk

script:
- ./run-ci.sh
