sudo: required
dist: trusty

language: cpp

compiler: gcc

before_script:
-  sudo apt-get update
-  sudo apt-get install -y ragel  gawk libtool  cmake  
-  sudo apt-get install -y libboost-all-dev libevent-dev 
-  sudo apt-get install -y libyaml-dev zlib1g-dev liblzma-dev 
-  sudo apt-get install -y postgresql-server-dev-all 
-  sudo apt-get install -y libsqlite3-dev
-  sudo apt-get install -y libjsoncpp-dev
-  sudo apt-get install -y  bison flex
-  ./prep-env.sh

script:
-  ./run-all.sh
